version: 3.8

services:
  redis:
      image: docker.io/bitnami/redis:7.2
      restart: always
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      ports:
        - '6379:6379'